name: Tests

on:
    push:
        branches:
            - master

jobs:
    build-test:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'
            - run: npm install
            - run: npm build
            - run: npm test
